<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdDy5Qy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdDy5Qy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdDy5Qy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdDy5Qy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXdDy5Qy\App_KernelDevDebugContainer([
    'container.build_hash' => 'XdDy5Qy',
    'container.build_id' => 'f678dd12',
    'container.build_time' => 1722069809,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdDy5Qy');
